[general]
import = [
    "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[window]
dimensions = { columns = 135, lines = 30 }
position = "None"
padding = { x = 4, y = 2 }
dynamic_padding = true
decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Maximized"
title = "Alacritty"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
size = 11.0
